codes = {'Accounting': 'ACCT',
         'Actuarial Science': 'ACTU',
         'African American and African Diaspora': 'AFAM',
         'Africana Studies': 'AFSB',
         'American Language Program': 'AMLP',
         'American Studies': 'AMST',
         'American Studies @Barnard': 'AMSB',
         'Anesthesiology': 'ANES',
         'Anthropology': 'ANTH',
         'Anthropology @Barnard': 'ANTB',
         'Applied Analytics': 'APAN',
         'Applied Physics and Applied Mathematics': 'APAM',
         'Architecture @Barnard': 'ARCB',
         'Architecture, Planning and Preservation': 'ARPL',
         'Art History @Barnard': 'ARHB',
         'Art History and Archaeology': 'AHAR',
         'Arts, School of the': 'ARTS',
         'Asian and Middle East @Barnard': 'ASMB',
         'Astronomy': 'ASTR',
         'Athena Center for Leadership Studies @Barnard': 'ACLB',
         'Bioethics': 'BIET',
         'Biological Sciences': 'BIOS',
         'Biological Sciences @ Barnard': 'BIOB',
         'Biomedical Engineering': 'BMEN',
         'Biomedical Informatics': 'BINF',
         'Biostatistics': 'BIST',
         'Business': 'BUSI',
         'Business Economics': 'BUEC',
         'Cellular, Molecular, and Biophysical Studies': 'CMBS',
         'Chemical Engineering': 'CHEN',
         'Chemistry': 'CHEM',
         'Chemistry @Barnard': 'CHMB',
         'Civil Engineering and Engineering Mechanics': 'CEEM',
         'Classics': 'CLAS',
         'Classics @Barnard': 'CLSB',
         'Columbia College': 'COLL',
         'Committee on Global Thought': 'CGTH',
         'Comparative Literature and Society @Barnard': 'CSOB',
         'Comparative Literature and Society, Institute for': 'CCLS',
         'Computer Science': 'COMS',
         'Computer Science @Barnard': 'COMB',
         'Consortium for Critical Interdisciplinary Studies @Barnard': 'CCIB',
         'Construction Administration': 'CNAD',
         'Core (A&S)': 'CORE',
         'Dance @Barnard': 'DANB',
         'Decision, Risk and Operations': 'DROM',
         'Dental and Oral Surgery': 'DEOS',
         'Earth and Environmental Engineering': 'EAEE',
         'Earth and Environmental Sciences': 'EESC',
         'Earth Institute': 'EI',
         'East Asian Languages and Cultures': 'EALC',
         'Ecology, Evolution, and Environmental Biology': 'EEEB',
         'Economics': 'ECON',
         'Economics @Barnard': 'ECOB',
         'Education @Barnard': 'EDNB',
         'Electrical Engineering': 'ELEN',
         'Engineering': 'ENGI',
         'English @Barnard': 'ENGB',
         'English and Comparative Literature': 'ENCL',
         'Enterprise Risk Management': 'ERM',
         'Environmental Health Sciences': 'EHSC',
         'Environmental Sciences @Barnard': 'ENSB',
         'Epidemiology': 'EPID',
         'Epidemiology: Exec Master Program': 'EXEP',
         'Ethnicity and Race, Center for': 'CSER',
         'Executive Classes in HPM': 'EXEC',
         'Film': 'FILM',
         'Film @Barnard': 'FLMB',
         'Finance': 'FINC',
         'First-Year Seminar Program @Barnard': 'FYSB',
         'First-Year Writing @Barnard': 'FYWB',
         'French @Barnard': 'FRNB',
         'French and Romance Philology': 'FRRP',
         'Genetics and Development': 'GEND',
         'German @Barnard': 'GRMB',
         'Germanic Languages': 'GERL',
         'Graduate School of Arts and Sciences': 'GSAS',
         'Health Policy & Management': 'HPMN',
         'History': 'HIST',
         'History @Barnard': 'HSTB',
         'Human Capital Management': 'HCM',
         'Human Rights (HRTB)': 'HRTB',
         'Industrial Engineering and Operations Research': 'IEOR',
         'Information & Knowledge Strat': 'IKNS',
         'Institute for Israel & Jewish Studies': 'IIJS',
         'Institute for Study of Human Rights': 'CSHR',
         'Insurance Management': 'IMGT',
         'International and Public Affairs': 'INTA',
         'Italian': 'ITAL',
         'Italian @Barnard': 'ITLB',
         'Jazz Studies, Center for': 'CJAZ',
         'Journalism': 'JOUR',
         'Language Resource Center': 'LRC',
         'Latin American and Iberian Cultures': 'SPPO',
         'Latin-American & Carib RS': 'LCRS',
         'Law': 'LAW'
         }


tech_electives = {'Accounting', 'Actuarial Science', 'Applied Analytics', 'Applied Physics and Applied Mathematics',
                  'Astronomy',
                  'Computer Science', 'Computer Science @Barnard',
                  'Electrical Engineering', 'Engineering', 'Ecology, Evolution, and Environmental Biology'}
